name: First Workflow
#on: workflow_dispatch
jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Prnt Greeting
        run: echo "Hello there"
      - name: Say goodBuy
        run: echo "good buy!"
